name: Build and Deploy Docker Image

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '**'

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Docker availability
        run: docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t mern-fe:${{ github.sha }} ./client
          docker push mern-fe:${{ github.sha }}

      - name: Build and push backend Docker image
        run: |
          docker build -t mern-be:${{ github.sha }} ./server
          docker push mern-be:${{ github.sha }}

  create_ec2:
    runs-on: ubuntu-latest
    needs: build-upload
    steps:
      - uses: actions/checkout@v3

      # Add AWS credentials setup step here...

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Create EC2 instance
        working-directory: .github/IaC
        run: |
          # Add Terraform apply command here...

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-upload
      - create_ec2
    steps:
      - uses: actions/checkout@v3

      # Add AWS credentials setup step here...

      - name: Update MERN app on EC2
        working-directory: .github/scripts
        run: |
          # Add deployment script command here...
