 name: Build and Deploy Docker Image

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker availability
        run: docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t mern-fe:${{ github.sha }} ./client
          docker tag mern-fe:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mern-fe:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-fe:${{ github.sha }}

      - name: Build and push backend Docker image
        run: |
          docker build -t mern-be:${{ github.sha }} ./server
          docker tag mern-be:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mern-be:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-be:${{ github.sha }}

  create_ec2:
    runs-on: ubuntu-latest
    needs: build-upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Apply Terraform configuration
        working-directory: .github/IaC
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply tfplan -auto-approve

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-upload
      - create_ec2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Update MERN app on EC2
        working-directory: .github/scripts
        run: |
          # Execute deployment script to update the MERN app on EC2 instance
          bash deploy.sh
